// swift-tools-version:5.3

import PackageDescription

let package = Package(
    name: "RongmaiKit",
    products: [
        .library(
            name: "RongmaiKit",
            targets: [
                "RongmaiKit",

                "CoreModules",
                "React_runtimescheduler",
                "DoubleConversion",
                "React_utils",
                "SocketRocket",
                "RCTAnimation",
                "cxxreact",
                "RCTBlob",
                "fmt",
                "RCTImage",
                "folly",
                "RCTLinking",
                "glog",
                "RCTNetwork",
                "hermes",
                "RCTSettings",
                "RCTText",
                "jsi",
                "RCTTypeSafety",
                "jsinspector",
                "RCTVibration",
                "jsireact",
                "React",
                "libevent",
                "ReactCommon",
                "logger",
                "React_Codegen",
                "reacthermes",
                "React_NativeModulesApple",
                "reactperflogger",
                "React_RCTAppDelegate",
                "yoga",
                "React_debug",

                "react_native_netinfo",
                "RNCAsyncStorage",
                "RNDeviceInfo",
            ]),
    ],
    dependencies: [],
    targets: [
        .binaryTarget(name: "RongmaiKit", path: "xc/RongmaiKit.xcframework"),

        .binaryTarget(name: "CoreModules", path: "xc/CoreModules.xcframework"),
        .binaryTarget(name: "React_runtimescheduler", path: "xc/React_runtimescheduler.xcframework"),
        .binaryTarget(name: "DoubleConversion", path: "xc/DoubleConversion.xcframework"),
        .binaryTarget(name: "React_utils", path: "xc/React_utils.xcframework"),
        .binaryTarget(name: "SocketRocket", path: "xc/SocketRocket.xcframework"),
        .binaryTarget(name: "RCTAnimation", path: "xc/RCTAnimation.xcframework"),
        .binaryTarget(name: "cxxreact", path: "xc/cxxreact.xcframework"),
        .binaryTarget(name: "RCTBlob", path: "xc/RCTBlob.xcframework"),
        .binaryTarget(name: "fmt", path: "xc/fmt.xcframework"),
        .binaryTarget(name: "RCTImage", path: "xc/RCTImage.xcframework"),
        .binaryTarget(name: "folly", path: "xc/folly.xcframework"),
        .binaryTarget(name: "RCTLinking", path: "xc/RCTLinking.xcframework"),
        .binaryTarget(name: "glog", path: "xc/glog.xcframework"),
        .binaryTarget(name: "RCTNetwork", path: "xc/RCTNetwork.xcframework"),
        .binaryTarget(name: "hermes", path: "xc/hermes.xcframework"),
        .binaryTarget(name: "RCTSettings", path: "xc/RCTSettings.xcframework"),
        .binaryTarget(name: "RCTText", path: "xc/RCTText.xcframework"),
        .binaryTarget(name: "jsi", path: "xc/jsi.xcframework"),
        .binaryTarget(name: "RCTTypeSafety", path: "xc/RCTTypeSafety.xcframework"),
        .binaryTarget(name: "jsinspector", path: "xc/jsinspector.xcframework"),
        .binaryTarget(name: "RCTVibration", path: "xc/RCTVibration.xcframework"),
        .binaryTarget(name: "jsireact", path: "xc/jsireact.xcframework"),
        .binaryTarget(name: "React", path: "xc/React.xcframework"),
        .binaryTarget(name: "libevent", path: "xc/libevent.xcframework"),
        .binaryTarget(name: "ReactCommon", path: "xc/ReactCommon.xcframework"),
        .binaryTarget(name: "logger", path: "xc/logger.xcframework"),
        .binaryTarget(name: "React_Codegen", path: "xc/React_Codegen.xcframework"),
        .binaryTarget(name: "reacthermes", path: "xc/reacthermes.xcframework"),
        .binaryTarget(name: "React_NativeModulesApple", path: "xc/React_NativeModulesApple.xcframework"),
        .binaryTarget(name: "reactperflogger", path: "xc/reactperflogger.xcframework"),
        .binaryTarget(name: "React_RCTAppDelegate", path: "xc/React_RCTAppDelegate.xcframework"),
        .binaryTarget(name: "yoga", path: "xc/yoga.xcframework"),
        .binaryTarget(name: "React_debug", path: "xc/React_debug.xcframework"),

        .binaryTarget(name: "react_native_netinfo", path: "xc/react_native_netinfo.xcframework"),
        .binaryTarget(name: "RNCAsyncStorage", path: "xc/RNCAsyncStorage.xcframework"),
        .binaryTarget(name: "RNDeviceInfo", path: "xc/RNDeviceInfo.xcframework"),
    ]
)
